name: Request for Mozilla Position on an Emerging Web Specification
description: If you're working on a spec and would like to know the Mozilla's position on it, this is the form for you!
body:
  - type: markdown
    attributes:
      value: "## Mozillians who can provide input"
  - type: input
    id: mozillians
    attributes:
      label: "Mozillians"
      description: "Who from the Mozilla community do you think is best positioned to review this spec? It's okay if you don't know."
      placeholder: "@zcorpan @tantek"
  - type: markdown
    attributes:
      value: "## Information about the specification or proposal"
  - type: input
    id: spec-title
    attributes:
      label: "Title of the spec"
      placeholder: "CSS Frobnication Module, Level 5"
    validations:
      required: true
  - type: input
    id: spec-link
    attributes:
      label: "URL to the spec"
      placeholder: "https://www.w3.org/TR/SHORTNAME"
    validations:
      required: true
  - type: input
    id: spec-repo
    attributes:
      label: "URL to the spec's repository"
      description: "On GitHub or whatever repository hosting provider the spec uses."
      placeholder: "https://github.com/ORG/REPO"
  - type: input
    id: spec-issues
    attributes:
      label: "Issue Tracker URL"
      description: "Only supply this if the spec doesn't use GitHub for issue tracking"
  - type: input
    id: spec-explainer
    attributes:
      label: "Explainer URL"
      description: "Only supply this if the explainer isn't the README.md in the GitHub repo"
  - type: markdown
    attributes:
      value: "## Design reviews and vendor positions"
  - type: input
    id: tag-review
    attributes:
      label: "TAG Design Review URL"
      placeholder: "https://github.com/w3ctag/design-reviews/issues/NNN"
  - type: input
    id: moz-position
    attributes:
      label: "WebKit standards-positions issue URL"
      placeholder: "https://github.com/WebKit/standards-positions/issues/NNN"
  - type: markdown
    attributes:
      value: "## Bugs tracking this feature"
  - type: input
    id: mozilla-bugzilla
    attributes:
      label: "Mozilla Bugzilla URL"
      placeholder: "https://bugzilla.mozilla.org/show_bug.cgi?id=NNNNNN"
  - type: input
    id: radar
    attributes:
      label: "Caniuse URL"
      placeholder: "https://caniuse.com/NNNNNNNNN"
  - type: markdown
    attributes:
      value: "## Anything else we need to know"
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: |
        Please tell us what the proposal or specification is.

        Include any details or salient information you think will aid us in coming to a position.
    validations:
      required: true
