name: Request for Mozilla Position on an Emerging Web Specification
body:
  - type: input
    id: spec-title
    attributes:
      label: "Specification title"
    validations:
      required: true
  - type: input
    id: spec-url
    attributes:
      label: "Specification or proposal URL (if available)"
      placeholder: "https://"
  - type: input
    id: spec-explainer
    attributes:
      label: "Explainer URL (if available)"
      placeholder: "https://"
  - type: input
    id: spec-authors
    attributes:
      label: "Proposal author(s) (`@`-mention GitHub accounts)"
      placeholder: "@handle, @another"
    validations:
      required: true
  - type: input
    id: caniuse-url
    attributes:
      label: "Caniuse.com URL"
      placeholder: "https://"
  - type: input
    id: bugzilla-url
    attributes:
      label: "Bugzilla URL"
      placeholder: "https://bugzilla.mozilla.org/show_bug.cgi?id="
  - type: input        
    id: mozillians
    attributes:
      label: "Mozillians who can provide input"
      placeholder: "@handle, @another"
  - type: input
    id: webkit-standards-position
    attributes:
      label: "WebKit standards-position"
      placeholder: "https://github.com/WebKit/standards-positions/issues"
    validations:
      required: true


