name: Build and Deploy

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to support rebasing

      - name: Set up SSH for Git (deploy key)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch and Check Out `gh-pages`
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch and switch to `gh-pages`
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Rebase `gh-pages` onto `main` (if triggered by push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git rebase main

      - name: Generate Merged Data
        run: |
          python3 gh-data.py
          python3 merge-data.py

      - name: Commit and Push Updates
        run: |
          # Add changes
          git add -f merged-data.json

          # Commit changes if there are any
          git commit -m "Update GitHub Pages with latest data"

          # Push changes back to `gh-pages`
          git remote set-url origin git@github.com:${{ github.repository }}.git
          git push origin gh-pages --force
